"""added check for answer spaces

Revision ID: 36ee8e2bc03e
Revises: 5fbe7423f80e
Create Date: 2019-08-22 10:41:32.065309

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '36ee8e2bc03e'
down_revision = '5fbe7423f80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_space', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('answer_space')

    # ### end Alembic commands ###
