"""updated paper fields

Revision ID: 5fbe7423f80e
Revises: bd8f490b2b12
Create Date: 2019-08-21 15:57:08.360230

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5fbe7423f80e'
down_revision = 'bd8f490b2b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rules', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.drop_column('subject')
        batch_op.drop_column('rules')
        batch_op.drop_column('duration')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
