"""changed to text from varchar

Revision ID: 650ec7539ccd
Revises: 5a6be900ac2d
Create Date: 2019-08-07 17:35:27.900892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650ec7539ccd'
down_revision = '5a6be900ac2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
