"""remove hybrid, added pos to quin

Revision ID: 8285c6d93acb
Revises: de04dda17814
Create Date: 2019-08-15 07:53:22.075703

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8285c6d93acb'
down_revision = 'de04dda17814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.drop_column('question_order')

    with op.batch_alter_table('question_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_in', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_order', sa.VARCHAR(), server_default=sa.text("'[]'"), nullable=False))

    # ### end Alembic commands ###
