"""setting up papers

Revision ID: 8fb7fe09c39f
Revises: fb02383088f1
Create Date: 2019-08-02 08:56:09.307223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb7fe09c39f'
down_revision = 'fb02383088f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_date_created'), 'paper', ['date_created'], unique=False)
    op.create_index(op.f('ix_paper_name'), 'paper', ['name'], unique=False)
    op.create_table('question_in',
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_in')
    op.drop_index(op.f('ix_paper_name'), table_name='paper')
    op.drop_index(op.f('ix_paper_date_created'), table_name='paper')
    op.drop_table('paper')
    # ### end Alembic commands ###
