"""removed paper postion in question_in table

Revision ID: a37c8f17fbb0
Revises: 4f44444d8478
Create Date: 2019-08-15 06:41:01.990241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37c8f17fbb0'
down_revision = '4f44444d8478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
