"""changed level to exam_level

Revision ID: f491c7d33d0f
Revises: 650ec7539ccd
Create Date: 2019-08-08 10:58:21.030159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f491c7d33d0f'
down_revision = '650ec7539ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
