"""going with string and json

Revision ID: fdd2b1b17683
Revises: 8285c6d93acb
Create Date: 2019-08-15 08:14:56.563395

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'fdd2b1b17683'
down_revision = '8285c6d93acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('positions', sa.String(), nullable=True))

    with op.batch_alter_table('question_in', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.drop_column('positions')

    # ### end Alembic commands ###
