"""examlevels

Revision ID: bec02f13164f
Revises: 8fb7fe09c39f
Create Date: 2019-08-06 07:29:18.076068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec02f13164f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_level_name'), 'exam_level', ['name'], unique=True)
    op.add_column('paper', sa.Column('level', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paper', 'exam_level', ['level'], ['id'])
    op.add_column('question', sa.Column('level', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'exam_level', ['level'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'level')
    op.drop_constraint(None, 'paper', type_='foreignkey')
    op.drop_column('paper', 'level')
    op.drop_index(op.f('ix_exam_level_name'), table_name='exam_level')
    op.drop_table('exam_level')
    # ### end Alembic commands ###
