"""exam levels

Revision ID: e3b709e6a201
Revises: bec02f13164f
Create Date: 2019-08-06 08:06:59.006319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b709e6a201'
down_revision = 'bec02f13164f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'paper', 'exam_level', ['level'], ['id'])
    op.create_foreign_key(None, 'question', 'exam_level', ['level'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'paper', type_='foreignkey')
    # ### end Alembic commands ###
