"""added question order list

Revision ID: 72357835a317
Revises: a37c8f17fbb0
Create Date: 2019-08-15 06:44:45.122310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72357835a317'
down_revision = 'a37c8f17fbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_order', sa.ARRAY(sa.Integer()), nullable=True))

    with op.batch_alter_table('question_in', schema=None) as batch_op:
        batch_op.drop_column('paper_position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_position', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.drop_column('question_order')

    # ### end Alembic commands ###
